name: analyze terraform

on:
  pull_request:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed_files.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get specific changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.0.2
        with:
          separator: ','
          files: |
            modules/module1
            modules/module2
            modules/module3
            modules/s3

      - name: List all modified/added files
        id: changed_files
        run: |
          modules=(module1 module2 module3 s3)
          modified_files=${{ steps.changed-files.outputs.all_modified_files }}

          echo $modified_files

          for module in ${modules[@]}; do
              if [[ ${modified_files[*]} =~ $module ]]; then
                  changed_files+=($module)
              fi
          done

          echo "::set-output name=matrix::$(printf '%s\n' "${changed_files[@]}" | jq -cnR '[inputs | select(length>0)]')"

  analyse_module:
    runs-on: ubuntu-latest
    needs: check_files
    strategy:
      matrix:
        module: ${{ fromJson(needs.check_files.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules/${{ matrix.module }}
          config_file: modules/${{ matrix.module }}/configure.yml
